name: simple_sheet_music
description: A Flutter package for rendering sheet music on canvas. This package provides a simple way to display sheet music in a Flutter application. It includes classes for rendering staffs, measures, clefs, notes, and other music objects.
version: 1.0.0
homepage: https://github.com/tomoyu719/simple_sheet_music

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  flutter:
    sdk: flutter
  golden_toolkit: ^0.15.0
  svg_path_parser: ^1.1.2
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  # fonts:
  #     - family: Bravura
  #       fonts:
  #           - asset: assets/Bravura.otf
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/Bravura.svg
    - assets/bravura_metadata.json
    - assets/Petaluma.svg
    - assets/petaluma_metadata.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
