name: Unit tests run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # allow manual execution


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "12.x"
   
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get
        
      - name: library unit tests
        run: flutter test

      # - name: example unit tests
      #   working-directory: example
      #   run: flutter test

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          retention-days: 14
          name: /test-artifacts
          path: /test/failures/**  
      